services:
  db:
    container_name: fichajespi_db
    image: mariadb:11.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=fichajesroot #Cambiar password si se desea
      - TZ=Europe/Madrid
      - MYSQL_DATABASE=db_fichajespi
      - MYSQL_USER=fichajes #Cambiar usuario si se desea
      - MYSQL_PASSWORD=b93U5DA9M7NqjUHgbxQ0nh8T9 #Cambiar password si se desea
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  backendserver:
    container_name: fichajespi_back
    build: ./spring-boot_fichajesPi/
    environment:
      - TZ=Europe/Madrid
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_fichajespi
      - SPRING_DATASOURCE_USERNAME=fichajes #Usar mismo usuario que la base de datos
      - SPRING_DATASOURCE_PASSWORD=fichajes #Usar misma contraseña que la base de datos
      - CLIENT_URL=http://192.168.0.113
      - SPRING_MAIL_HOST=smtp.mailtrap.io #poner dominio del servidor smtp
      - SPRING_MAIL_PORT=2525 #poner puerto del servidor smtp
      - SPRING_MAIL_USERNAME=maze #Nombre usuario servidor correos
      - SPRING_MAIL_PASSWORD=b93U5DA9M7NqjUHgbxQ #Password servidor correos
      - JWT_SECRET=b93U5DA9M7NqjUHg #Secret key for JWT tokens
    ports:
      - "8080:8080"
    links:
      - "db"
    depends_on:
      - "db"
    restart: always

  frontend:
    container_name: fichajespi_front
    build:
      context: ./angular_fichajesPi/
      args:
        - apiURL=http://192.168.0.113:8080
    ports:
      - "80:80"
    environment:
      - TZ=Europe/Madrid
    restart: always

  phpmyadmin:
    container_name: fichajespi_dbadmin
    image: arm64v8/phpmyadmin:latest
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    restart: always

volumes:
  db_data:
