services:
  db:
    image: linuxserver/mariadb:10.5.13
    environment:
      - MYSQL_ROOT_PASSWORD= #añadir contraseña
      - TZ=Europe/Madrid
      - MYSQL_DATABASE=db_fichajespi #puedes añadir propio
      - MYSQL_USER=fichajes #puedes añadir propio
      - MYSQL_PASSWORD= #añadir contraseña
    restart: always
    volumes:
      - $HOME/database_data:/config/databases
      - $HOME/database_logs:/config/logs
    networks:
      - db

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "81:80"
    environment:
      - PMA_ARBITRARY=1
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - db

  frontend:
    image: fichajespi_front:latest
    ports:
      - "80:80"
    environment:
      - TZ=Europe/Madrid
    restart: always
    networks:
      - backend

  backend:
    image: fichajespi_back:latest
    
    environment:
      - TZ=Europe/Madrid

      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_fichajespi
      - SPRING_DATASOURCE_USERNAME=fichajes
      - SPRING_DATASOURCE_PASSWORD= #añadir contraseña 

      # Ajusta esto según cómo lo use tu backend 
      - CLIENT_URL=http://localhost

      - SPRING_MAIL_HOST= #puedes añadir propio
      - SPRING_MAIL_PORT= #añadir propio
      - SPRING_MAIL_USERNAME= #añadir propio
      - SPRING_MAIL_PASSWORD= #añadir contraseña
      - JWT_SECRET= #añadir secret
    ports:
      - "8080:8080"
    restart: always
    networks:
      - backend
      - db

networks:
  backend:
  db:

volumes:
  db:
